apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: zookeeper-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Zookeeper is the Schema for the zookeepers API
      displayName: Zookeeper
      kind: Zookeeper
      name: zookeepers.bigdata.kubernetesbigdataeg.org
      version: v1alpha1
  description: Zookeeper operator for testing
  displayName: Zookeeper
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - zk
  - zookeeper
  - big data
  links:
  - name: Zookeeper Operator
    url: https://zookeeper-operator.domain
  maturity: alpha
  provider:
    name: Big Data Engineering Group
  version: 0.0.0
